package apply_template

import (
	"fmt"
	"os"
	"text/template"
)

type ReturnValueType uint8

const (
	// no return value
	Exec ReturnValueType = 1
	// 1 row
	QueryRow ReturnValueType = 2
	// multi rows of simple type
	QueryPlain ReturnValueType = 3
	// multi rows of struct type
	QueryStruct ReturnValueType = 4
)

type Variable struct {
	Name string
	Type string
}

type Function struct {
	Name            string
	SQL             string
	InputArguments  []Variable
	ReturnValueType ReturnValueType
	// Exec: no return arguments, autogenerated "(err error)"
	// QueryRow: one or more simple return arguments, ", err error)" will be autogenerated
	OutputArguments []Variable
	// QueryPlain: two arguments - []simpleType and ", err error)"
	UnderlyingTypeName string
	// QueryStruct: two arguments - []structType and ", err error)"
	// RowFieldsNames have names of struct
	RowFieldsNames []string
}

// Render in template as "{{ . }}"
type DotType struct {
	PackageName string
	Packages    []string
	Functions   []Function
}

func Render(tt DotType) error {
	t, err := template.New("GoDao").Parse(templateEmbedded)
	if err != nil {
		return fmt.Errorf("text/template.Template.Parse(): %w", err)
	}

	err = t.Execute(os.Stdout, tt)
	if err != nil {
		return fmt.Errorf("text/template.Template.Execute(): %w", err)
	}

	return nil
}
