package main

import (
	"bufio"
	"log"
	"os"
)

//go:generate go run ./embed.go

func main()  {
	fromF, err := os.Open("./dao.go.tmpl")
	if err != nil {
		log.Fatal(err)
	}
	defer fromF.Close()
	fromB := bufio.NewReader(fromF)

	toF, err := os.Create("../template_embedded.go")
	if err != nil {
		log.Fatal(err)
	}
	defer toF.Close()
	toB := bufio.NewWriter(toF)
	defer toB.Flush()

	toB.WriteString("// This file is automatically generated. Do not edit it.\npackage apply_template\n\nconst templateEmbedded = \"")

	for {
		b, err := fromB.ReadByte()
		if err != nil {
			break
		}

		switch b {
		case byte('\n'):
			toB.WriteString("\\n")
		case byte('"'):
			toB.WriteString("\\\"")
		default:
			toB.WriteByte(b)
		}
	}

	toB.WriteString("\"\n")
}
